import NextHead from 'next/head'
import {
	Box,
	useColorMode,
	Flex,
	Heading,
	Text,
	chakra,
	Code,
	useToken,
	useColorModeValue
} from '@chakra-ui/react'
import Link from '@components/Link'
import VercelIcon from '@components/VercelIcon'

const Head = () => (
	<NextHead>
		<title>Next JS + Chakra UI Starter</title>
		<meta name='description' content='Generated by create next app' />
		<link rel='icon' href='/favicon.ico' />
	</NextHead>
)

const Card = ({ href, title, description }) => {
	const [teal300, gray200] = useToken('colors', ['teal.300', 'gray.200'])

	return (
		<Link
			isExternal
			href={href}
			m={4}
			p={6}
			textAlign='left'
			border={`1px solid ${gray200}`}
			borderRadius={12}
			transition='0.15s all ease-in-out'
			maxW='340px'
			color='inherit'
			textDecoration='none'
			_hover={{ color: teal300, borderColor: teal300 }}
			_active={{ color: teal300, borderColor: teal300 }}
		>
			<Heading as='h2' fontSize='1.5rem'>
				{title} &rarr;
			</Heading>
			<Text fontSize='1.25rem'>{description}</Text>
		</Link>
	)
}

export default function Home() {
	const { toggleColorMode } = useColorMode()

	return (
		<Box px={2}>
			<Head />

			<Flex
				as='main'
				maxH='100hv'
				flexDir='column'
				justify='center'
				alignItems='center'
				flex={1}
				py={14}
			>
				<Heading>
					Welcome to{' '}
					<Link isExternal color='teal.300' href='https://nextjs.org'>
						Next.js!
					</Link>
				</Heading>

				<Text
					as='button'
					textAlign='center'
					fontSize='1rem'
					mt={2}
					textDecoration='underline'
					cursor='pointer'
					_hover={{ color: 'teal.300' }}
					onClick={toggleColorMode}
				>
					Switch theme
				</Text>

				<Text textAlign='center' fontSize='1.3rem' my={6}>
					Get started by editing{' '}
					<Code children='pages/index.js' fontSize='1.2rem' />
				</Text>

				<Flex
					align='center'
					justify='center'
					flexWrap='wrap'
					maxW={800}
					w='100%'
					flexDir={['column', 'row']}
				>
					<Card
						href='https://nextjs.org/docs'
						title='NextJS Docs'
						description='Find in-depth information about Next.js features and API.'
					/>

					<Card
						href='https://nextjs.org/learn'
						title='Learn NextJS'
						description='Learn about Next.js in an interactive course with quizzes!'
					/>

					<Card
						href='https://github.com/vercel/next.js/tree/canary/examples'
						title='NextJS Examples'
						description='Discover and deploy boilerplate example Next.js projects.'
					/>

					<Card
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						title='Deploy'
						description='Instantly deploy your Next.js site to a public URL with Vercel.'
					/>

					<Card
						href='https://chakra-ui.com/docs'
						title='Chakra UI Docs'
						description='Learn how to use the Chakra UI components.'
					/>
				</Flex>
			</Flex>

			<chakra.footer
				display='flex'
				flex={1}
				py={4}
				borderTop='1px solid #eaeaea'
				justifyContent='center'
				alignItems='center'
				flexDir='row'
			>
				<Flex justifyContent='center' alignItems='center'>
					<Link
						isExternal
						href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					>
						Powered by{' '}
						<chakra.span ml={2} display='inline-block'>
							<VercelIcon
								fill={useColorModeValue('#000', '#fff')}
								width='18'
								height='4'
							/>
						</chakra.span>
					</Link>
				</Flex>
			</chakra.footer>
		</Box>
	)
}
